.\" Copyright (c) 2013-2014 Radoslaw Kujawa. All Rights Reserved.
.Dd January 19, 2014
.Dt 9TCFG 
.Os "Ninetails"
.Sh NAME
.Nm 9tcfg 
.Nd Ninetails accelerator configuration program 
.Sh SYNOPSIS
.Nm
.Op M68K/T
.Op M68KMEM/T 
.Op PCMCIA/T
.Op MAPROM/T
.Op SHADOWROM/T 
.Op LOADROM/K 
.Op MOREMEM/S 
.Op INSTCACHE/T 
.Op REBOOT/S
.Op DEBUG/S
.Op HELP/S
.Sh DESCRIPTION
The 
.Nm
command can be used to manage additional functions of Ninetails accelerator board.
The
.Nm
command takes the following flags and arguments:
.Bl -tag -width
.It M68K/T
68000 mode - disable/enable the 68020 processor after next reboot (off by default).
.It M68KMEM/T
68000 mode + Fast RAM - as above but with 5.5MB of Fast (off by default).
.It INSTCACHE/T 
Turn off/on instruction cache (on by default).
.It PCMCIA/T
Enable PCMCIA access, configure only 4MB of RAM.
.It MAPROM/T
Enable/disable the MAPROM function, must be used with LOADROM/K (off by default).
.It SHADOWROM/T 
Enable/disable the Shadow ROM function, may not be used when MAPROM is enabled (off by default).
.It LOADROM/K 
Specify the Kickstart ROM file to load. Must be exactly 256kB, 512kB or 1MB.
.It REBOOT/S 
Reboot the Amiga after setting requrested options.
.It MOREMEM/S
Add 1,5MB of non-autoconfiguring Fast RAM to operating system memory list.
.It DEBUG/S
Print a lot of information useful only to developers.
.It HELP/S
Print help and exit.
.El
.Sh AUTHORS
Ninetails board was designed and produced by Rafal Chyla.
9tcfg was written by Radoslaw "strim" Kujawa.
